### ISSUE TITLE
ownCloud 7 HTTPS support

### ISSUE THREAD

**Issue by fxshpac** [ddurdle/ownCloud-for-KODI#14]
I just tried 0.4.4 version and I got script error when trying to open a folder which contains the videos. Following is the kodi log entry when that happens. Let me know if it's still intended behavior in this version.

23:28:36 T:2708   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: bad operand type for unary +: 'str'
                                            Traceback (most recent call last):
                                              File "C:\Users\[****]\AppData\Roaming\Kodi\addons\plugin.video.owncloud\default.py", line 329, in <module>
                                                addMediaFile(oc, isQuickLink, cacheType, item)
                                              File "C:\Users\[****]\AppData\Roaming\Kodi\addons\plugin.video.owncloud\default.py", line 83, in addMediaFile
                                                url = service.getMediaCall(package)
                                              File "C:\Users\[****]\AppData\Roaming\Kodi\addons\plugin.video.owncloud\resources\lib\owncloud.py", line 354, in getMediaCall
                                                return self.PLUGIN_URL+'?mode=audio&instance='+self.instanceName+'&filename='+fileID,+'&title='+fileID+'&directory=' + folderID
                                            TypeError: bad operand type for unary +: 'str'
                                            -->End of Python script error report<--
23:28:36 T:6720   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.owncloud/?directory=%2fOutbox%2fTopic1&instance=owncloud1&mode=folder
23:28:36 T:6720   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.owncloud/?directory=%2fOutbox%2fTopic1&instance=owncloud1&mode=folder) failed

**Comment by ddurdle** [comment]
OwnCloud 7 is out of support, closing.  Reopen if issue appears on >= 8
