### ISSUE TITLE
login information incorrect or permission is denied

### ISSUE THREAD

**Issue by h-2** [ddurdle/ownCloud-for-KODI#15]
... although I am pretty sure its correct. Maybe it doesn't cope with self-signed ssl-cert? Can I import it somewhere?

Thank you for your help!

**Server configuration**

Operating system: FreeBSD 10.1-RELEASE

Web server: lighttpd-1.4.35_5

Database: postgresql94-server-9.4.0

PHP version: php5-5.4.36

ownCloud version: owncloud-7.0.4

**Kodi**

Version: 14.0

Owncloud plugin: 0.4.5

**Comment by fatino** [comment]
Well it looks like python doesn't know about certificates imported via ca-certificates. I bundled my self-signed certificate there and it still doesn't know about it.

**Comment by ddurdle** [comment]
duplicate with - Self-signed certificates don't work. #16

**Comment by ddurdle** [comment]
Python community recommends upgrading Python on systems afflicted with this verification issue,rather than update and make python code insure by skipping validation of certificates.  Please upgrade Python on your KODI instance and reopen if necessary.

**Comment by ddurdle** [comment]
testing workaround in 0.4.9 
http://dmdsoftware.net/repository.ddurdle/plugin.video.owncloud-0.4.9.zip

**Comment by ddurdle** [comment]
testing workaround in 0.4.9 
http://dmdsoftware.net/repository.ddurdle/plugin.video.owncloud-0.4.9.zip

**Comment by h-2** [comment]
Still doesn't work for me, although I checked "self-signed cert" in the options. On the other hand the self-signed cert is also now "timed out", I don't know if thats a problem, I would really prefer a "ignore certificate problems" options, just to make sure. I will hopefully soon have letsencrypt and will try again then.

Thank you for your work!

**Comment by ddurdle** [comment]
The self-signed option ignores validating the certificate.  There might be some issue you are having.

**Comment by Spekkie** [comment]
I was getting the same message (login information incorrect or permission is denied), however it turned out NOT to be a certificate error but a problem in the login validation on line 206 of owncloud.py:
`loginResult != self.authorization.username):`
is containing the issue, since the username of owncloud is case insensitive so it actually logged in fine, but the above check is case sensitive which in my case caused the failure, but was still able to actually login and see all my files.

I'm still investigating why I can't play any files and if it's somehow related to this problem...

**Comment by ddurdle** [comment]
I'll fix this.

**Comment by fgarpe** [comment]
Hi!, I have the same message when I try to access to my owncloud using this addon:

login information incorrect or permission is denied

I have owncloud version 9.1.2 from appliance installer using self signed certificates from cacert.org.

I see this messages in the kodi.log

20:05:41 90455.687500 T:1305474032   ERROR: owncloud: login failed
20:05:41 90455.835938 T:1305474032   ERROR: owncloud: HTTP Error 401: Unauthorized

I'm sure that the login information is correct

Kodi version 16.1 from OSMC running on raspberry pi :´(

**Comment by ddurdle** [comment]
I will check into this.

**Comment by sankayop** [comment]
good evening,
I do have the same issue than fgarpe.
server Freebsd with owncloud 9.1.4 installed
raspberry pi 3 with kodi 16.1 via osmc
SSL certificate on and working for other apps

Moreover, in the choice of owncloud version, I can only chose between 6, 7 and 8.2 (no 9...?)

Thanks for your future help
