### ISSUE TITLE
On XBMC Kodi 14.0 Alpha 3, install error.

### ISSUE THREAD

**Issue by HLFH** [ddurdle/ownCloud-for-KODI#5]
On Kodi 14.0 Alpha 3, they said that the plugin does not have the correct structure

It would be cool to be compatible with XBMC Kodi 14.0 Code name “Helix” Alpha 3.

Because, for the moment, the plugin seems not to have the correct structure for Kodi version.

**Comment by uNiversaI** [comment]
What entry was that please for reference sake can you point it out?

**Comment by ddurdle** [comment]
The & in the description field as referenced in the change details.

**Comment by uNiversaI** [comment]
Ah yes, thanks for pointing it out.
